from tkinter import *
from tkinter import colorchooser
from tkinter import ttk
from tkinter import messagebox
import datetime
from datetime import date
import random
import time

bgcolors = ['red', 'green', 'blue', 'purple', 'pink', 'orange', 'lime', 'navy', 'black']
select_bg_1 = random.choice(bgcolors)
select_bg_2 = random.choice(bgcolors)
select_bg_3 = random.choice(bgcolors)


class Train(Toplevel):
    def __init__(self):
        Toplevel.__init__(self)
        self.title("Система купівлі залізничних квитків з міста Чернівці")
        self.geometry("1800x580+0+0")
        self.resizable("False","False")
        # self..configure(background='blue',border=0)

        # MainFrame = Frame(self., bd=10, width=1000, border=0, height=800,bg='white', relief=RIDGE)
        # MainFrame.grid()
        #
        # TopFrame1 = Frame(MainFrame, bd=10, width=1000, border=0, height=100,bg=None, relief=RIDGE)
        # TopFrame1.grid()
        #
        # TopFrame2 = Frame(MainFrame, bd=10, width=1100, border=0, height=500,bg=None, relief=RIDGE)
        # TopFrame2.grid()
        #
        # f1 = Frame(TopFrame2, width=890, height=500, border=0, bd=5,bg=None, relief=RIDGE)
        # f1.grid(row=1, column=0)
        #
        # f2 = Frame(TopFrame2, width=420, height=500, border=0, bd=5,bg=None, relief=RIDGE)
        # f2.grid(row=1, column=1)
        #
        # frametopRight = Frame(f2, bd=5, width=420, border=0, height=420,bg=None, relief=RIDGE)
        # frametopRight.pack(side=TOP)
        #
        # framebottomright = Frame(f2, bd=10, width=420, border=0, height=100,bg=None, relief=RIDGE)
        # framebottomright.pack(side=BOTTOM)
        #
        # f1a = Frame(f1, width=900, height=330, border=0, bd=5,bg=None, relief=RIDGE)
        # f1a.pack(side=TOP)
        #
        # f2a = Frame(f1, width=900, height=320, border=0, bd=5,bg=None, relief=RIDGE)
        # f2a.pack(side=BOTTOM)
        #
        # topLeft1 = Frame(f1a, width = 400, height = 200, border=0,bg=None, bd=5,padx=70,pady=1, relief=RIDGE)
        # topLeft1.pack(side=LEFT)
        # topLeft2 = Frame(f1a, width=300, height=200, border=0,bg=None, bd=5, relief=RIDGE)
        # topLeft2.pack(side=RIGHT)
        # topLeft3 = Frame(f1a, width=300, height=200, border=0,bg=None, bd=5, pady=1, relief=RIDGE)
        # topLeft3.pack(side=RIGHT)
        #
        # bottomLeft1 = Frame(f2a, width=450, height=200, border=0,bg=None, bd=5, pady=12, relief=RIDGE)
        # bottomLeft1.pack(side=LEFT)
        #
        # bottomLeft2 = Frame(f2a, width=450, height=200, border=0,bg=None, bd=5, relief=RIDGE)
        # bottomLeft2.pack(side=RIGHT)
        # ==============================================================================================================
        background_img = PhotoImage(file='Chernivtsi_station.gif')
        label_img = Label(self, image=background_img)
        label_img.pack()
        lblTitle = Label(self, font=('arial', 40, 'bold'), bg=None, text="Вокзал Чернівці", border=0, fg='navy',justify='center')
        lblTitle.place(x=660,y=0)
        # ==============================================================================================================

        date1 = StringVar()
        time1 = StringVar()
        Ticketclass = StringVar()
        TicketPrice = StringVar()
        Child_ticket = StringVar()
        Adult_ticket = StringVar()
        From_city = StringVar()
        To_city = StringVar()
        fee_price = StringVar()
        route = StringVar()
        receipt = StringVar()

        text_input = StringVar()
        global operator
        operator=""

        Ticketclass.set("")
        TicketPrice.set("")
        Child_ticket.set("")
        Adult_ticket.set("")
        From_city.set("")
        To_city.set("")
        fee_price.set("")
        route.set("")
        receipt.set("")

        var1 = IntVar()
        var2 = IntVar()
        var3 = IntVar()
        var4 = IntVar()
        var5 = IntVar()
        var6 = StringVar()
        var7 = StringVar()
        var8 = StringVar()
        var9 = StringVar()
        var10 = IntVar()
        var11 = IntVar()
        var12 = IntVar()
        var13 = StringVar()
        var14 = StringVar()
        var15 = StringVar()
        var16 = StringVar()

        tax = StringVar()
        subt = StringVar()
        total_pay = StringVar()

        var1.set("0")
        var2.set("0")
        var3.set("0")
        var4.set("0")
        var5.set("0")
        var6.set("0")
        var7.set("0")
        var8.set("0")
        var9.set("0")
        var10.set("0")
        var11.set("0")
        var12.set("0")
        var13.set("0")
        var14.set("0")
        var15.set("0")
        var16.set("")
        tax.set("₴ 0")
        subt.set("₴ 0")
        total_pay.set("₴ 0")
        #-------------------------------------------------Функції------------------------------------------------------
        # vars = var16
        #
        # def see_tickets():
        #     global vars
        #     history = Toplevel()
        #     history.title("Розглянення історії покупки квитків")
        #     # lb_history = Listbox(history, textvariable=vars)
        #     # lb_history.pack()
        #     history.mainloop()

        def exit():
            iExit = messagebox.askyesno("Системи подорожування з квитків", "Підтвердити, якщо ви хочете вийти")
            if iExit > 0:
                exit()

        def Reset():
            tax.set("₴ 0")
            subt.set("₴ 0")
            total_pay.set("₴ 0")
            var1.set("0")
            var2.set("0")
            var3.set("0")
            var4.set("0")
            var5.set("0")
            var6.set("0")
            var7.set("0")
            var8.set("0")
            var9.set("")
            var10.set("0")
            var11.set("0")
            var12.set("0")
            var13.set("0")
            var14.set("0")
            var15.set("0")
            var16.set("")

            Ticketclass.set("")
            TicketPrice.set("")
            Child_ticket.set("")
            Adult_ticket.set("")
            From_city.set("")
            To_city.set("")
            fee_price.set("")
            route.set("")
            receipt.set("")
            lblAdult1.config(text="Дорослий")
            lblChild1.config(text='Дитина')

        def command_help():
            colors = Toplevel()
            clr = colorchooser.askcolor(title='Виберіть кольори')
            print(clr)
            # self.config(bg=clr[1])
            # TopFrame2.config(bg=clr[1])
            # frametopRight.config(bg=clr[1])
            # framebottomright.config(bg=clr[1])
            # MainFrame.config(bg=clr[1])
            # topLeft1.config(bg=clr[1])
            # topLeft2.config(bg=clr[1])
            # topLeft3.config(bg=clr[1])
            # bottomLeft1.config(bg=clr[1])
            # TopFrame1.config(bg=clr[1])
            # f1.config(bg=clr[1])
            # f1a.config(bg=clr[1])
            # f2.config(bg=clr[1])
            # f2a.config(bg=clr[1])
            btnTotal.config(bg=clr[1])
            btnReset.config(bg=clr[1])
            lblTitle.config(bg=clr[1])
            label_adult.config(bg=clr[1])
            label_child.config(bg=clr[1])
            lblRef1.config(bg=clr[1])
            lblRef2.config(bg=clr[1])
            # chkPlackart.config(bg=clr[1])
            # chkSV.config(bg=clr[1])
            # chkKupe.config(bg=clr[1])
            # lblSelect.config(bg=clr[1])
            lblDestination.config(bg=clr[1])
            # lblsp.config(bg=clr[1])
            lblPrice1.config(bg=clr[1])
            lblPrice2.config(bg=clr[1])
            lblRoute1.config(bg=clr[1])
            lblRoute2.config(bg=clr[1])
            lblClass.config(bg=clr[1])
            lblAdult1.config(bg=clr[1])
            lblAdult2.config(bg=clr[1])
            lblChild1.config(bg=clr[1])
            lblChild2.config(bg=clr[1])
            lblclass1.config(bg=clr[1])
            lblclass2.config(bg=clr[1])
            lblDate1.config(bg=clr[1])
            lblDate2.config(bg=clr[1])
            lblFrom1.config(bg=clr[1])
            lblreceipt.config(bg=clr[1])
            lblTicket1.config(bg=clr[1])
            lblTicket2.config(bg=clr[1])
            # lblTicketType.config(bg=clr[1])
            labeltotal.config(bg=clr[1])
            colors.mainloop()

        def command_font_help():
            colors = Toplevel()
            fclr = colorchooser.askcolor(title='Виберіть кольори шрифту')
            print(fclr)
            btnTotal.config(fg=fclr[1])
            btnReset.config(fg=fclr[1])
            lblTitle.config(fg=fclr[1])
            label_adult.config(fg=fclr[1])
            label_child.config(fg=fclr[1])
            lblRef1.config(fg=fclr[1])
            lblRef2.config(fg=fclr[1])
            chkPlackart.config(fg=fclr[1])
            chkSV.config(fg=fclr[1])
            chkKupe.config(fg=fclr[1])
            lblSelect.config(fg=fclr[1])
            lblDestination.config(fg=fclr[1])
            # lblsp.config(fg=fclr[1])
            lblPrice1.config(fg=fclr[1])
            lblPrice2.config(fg=fclr[1])
            lblRoute1.config(fg=fclr[1])
            lblRoute2.config(fg=fclr[1])
            lblClass.config(fg=fclr[1])
            lblAdult1.config(fg=fclr[1])
            lblAdult2.config(fg=fclr[1])
            lblChild1.config(fg=fclr[1])
            lblChild2.config(fg=fclr[1])
            lblclass1.config(fg=fclr[1])
            lblclass2.config(fg=fclr[1])
            lblDate1.config(fg=fclr[1])
            lblDate2.config(fg=fclr[1])
            lblFrom1.config(fg=fclr[1])
            lblreceipt.config(fg=fclr[1])
            lblTicket1.config(fg=fclr[1])
            lblTicket2.config(fg=fclr[1])
            # lblTicketType.config(fg=fclr[1])
            labeltotal.config(fg=fclr[1])
            colors.mainloop()

        def travel_cost():
            if (var9.get() == "Київ" and var1.get() == 1 and var4.get() >= 1):
                tcost = float(195.5)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Плацкарт")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Київ")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Львів" and var1.get() == 1 and var4.get() >= 1):
                tcost = float(170.5)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Плацкарт")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Львів")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Одеса" and var1.get() == 1 and var4.get() >= 1):
                tcost = float(189.5)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Плацкарт")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Одеса")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)

            elif (var9.get() == "Ковель" and var1.get() == 1 and var4.get() >= 1):
                tcost = float(170.5)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Плацкарт")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Ковель")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Київ" and var2.get() == 1 and var4.get() >= 1):
                tcost = float(400.5)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Купе")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Київ")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Львів" and var2.get() == 1 and var4.get() >= 1):
                tcost = float(270.5)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Купе")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Львів")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Одеса" and var2.get() == 1 and var4.get() >= 1):
                tcost = float(380.5)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Купе")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Одеса")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)

            elif (var9.get() == "Ковель" and var2.get() == 1 and var4.get() >= 1):
                tcost = float(295.5)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Купе")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Ковель")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)

            elif (var9.get() == "Київ" and var3.get() == 1 and var4.get() >= 1):
                tcost = float(1560.5)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Люкс (СВ)")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Київ")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Львів" and var3.get() == 1 and var4.get() >= 1):
                tcost = float(600.5)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Люкс (СВ)")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Львів")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Одеса" and var3.get() == 1 and var4.get() >= 1):
                tcost = float(760.5)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Люкс (СВ)")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Одеса")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)

            elif (var9.get() == "Ковель" and var3.get() == 1 and var4.get() >= 1):
                tcost = float(540.5)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Люкс (СВ)")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Ковель")
                fee_price.set(totalcost)
                route.set("Прямий")
                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)

            elif (var9.get() == "Київ" and var1.get() == 1 and var5.get() >= 1):
                tcost = float(95.5)
                single = float(var5.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Плацкарт")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Київ")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Львів" and var1.get() == 1 and var5.get() >= 1):
                tcost = float(70.5)
                single = float(var5.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Плацкарт")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Львів")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Одеса" and var1.get() == 1 and var5.get() >= 1):
                tcost = float(89.5)
                single = float(var5.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Плацкарт")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Одеса")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)

            elif (var9.get() == "Ковель" and var1.get() == 1 and var5.get() >= 1):
                tcost = float(70.5)
                single = float(var5.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Плацкарт")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Ковель")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Київ" and var2.get() == 1 and var5.get() >= 1):
                tcost = float(300.5)
                single = float(var5.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Купе")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Київ")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Львів" and var2.get() == 1 and var5.get() >= 1):
                tcost = float(70.5)
                single = float(var5.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Купе")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Львів")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Одеса" and var2.get() == 1 and var5.get() >= 1):
                tcost = float(280.5)
                single = float(var5.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Купе")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Одеса")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)

            elif (var9.get() == "Ковель" and var2.get() == 1 and var5.get() >= 1):
                tcost = float(195.5)
                single = float(var5.get())
                adult_tax = " ₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Купе")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Ковель")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)

            elif (var9.get() == "Київ" and var3.get() == 1 and var5.get() >= 1):
                tcost = float(1460.5)
                single = float(var5.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Люкс (СВ)")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Київ")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Львів" and var3.get() == 1 and var5.get() >= 1):
                tcost = float(600.5)
                single = float(var5.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Люкс (СВ)")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Львів")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Одеса" and var3.get() == 1 and var5.get() >= 1):
                tcost = float(660.5)
                single = float(var5.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Люкс (СВ)")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Одеса")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)

            elif (var9.get() == "Ковель" and var3.get() == 1 and var5.get() >= 1):
                tcost = float(440.5)
                single = float(var5.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%(tcost * single))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Люкс (СВ)")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Ковель")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)

            elif (var9.get() == "Київ" and var1.get() == 1 and var4.get() >= 1 and var5.get() >= 1):
                tcost = float(290.5)
                Childcost = float(95.5)
                single = float(var4.get())
                single_child = float(var5.get())
                adult_tax = "₴", str('%.2f'%((tcost * Childcost * single * single_child)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * Childcost * single * single_child)))
                totalcost = "₴", str('%.2f'%((tcost * Childcost * single * single_child)+ ((tcost * Childcost * single * single_child)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Плацкарт")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Київ")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Львів" and var1.get() == 1 and var4.get() >= 1 and var5.get() >= 1):
                tcost = float(240.5)
                Childcost = float(70.5)
                single = float(var4.get())
                single_child = float(var5.get())
                adult_tax = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) * 0.27))
                adult_fees = "₴", str('%.2f' % ((tcost * Childcost * single * single_child)))
                totalcost = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) + (
                            (tcost * Childcost * single * single_child) * 0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Плацкарт")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Львів")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Одеса" and var1.get() == 1 and var4.get() >= 1 and var5.get() >= 1):
                tcost = float(278.5)
                Childcost = float(89.5)
                single = float(var4.get())
                single_child = float(var5.get())
                adult_tax = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) * 0.27))
                adult_fees = "₴", str('%.2f' % ((tcost * Childcost * single * single_child)))
                totalcost = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) + (
                            (tcost * Childcost * single * single_child) * 0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Плацкарт")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Одеса")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)

            elif (var9.get() == "Ковель" and var1.get() == 1 and var4.get() >= 1 and var5.get() >= 1):
                tcost = float(245.5)
                Childcost = float(70.5)
                single = float(var4.get())
                single_child = float(var5.get())
                adult_tax = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) * 0.27))
                adult_fees = "₴", str('%.2f' % ((tcost * Childcost * single * single_child)))
                totalcost = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) + (
                            (tcost * Childcost * single * single_child) * 0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Плацкарт")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Ковель")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Київ" and var2.get() == 1 and var4.get() >= 1 and var5.get() >= 1):
                tcost = float(700.5)
                Childcost = float(300.5)
                single = float(var4.get())
                single_child = float(var5.get())
                adult_tax = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) * 0.27))
                adult_fees = "₴", str('%.2f' % ((tcost * Childcost * single * single_child)))
                totalcost = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) + (
                            (tcost * Childcost * single * single_child) * 0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Купе")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Київ")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Львів" and var2.get() == 1 and var4.get() >= 1 and var5.get() >= 1):
                tcost = float(370.5)
                Childcost = float(70.5)
                single = float(var4.get())
                single_child = float(var5.get())
                adult_tax = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) * 0.27))
                adult_fees = "₴", str('%.2f' % ((tcost * Childcost * single * single_child)))
                totalcost = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) + (
                            (tcost * Childcost * single * single_child) * 0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Купе")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Львів")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Одеса" and var2.get() == 1 and var4.get() >= 1 and var5.get() >= 1):
                tcost = float(660.5)
                Childcost = float(280.5)
                single = float(var4.get())
                single_child = float(var5.get())
                adult_tax = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) * 0.27))
                adult_fees = "₴", str('%.2f' % ((tcost * Childcost * single * single_child)))
                totalcost = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) + (
                            (tcost * Childcost * single * single_child) * 0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Купе")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Одеса")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Ковель" and var2.get() == 1 and var4.get() >= 1 and var5.get() >= 1):
                tcost = float(490.5)
                Childcost = float(195.5)
                single = float(var4.get())
                single_child = float(var5.get())
                adult_tax = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) * 0.27))
                adult_fees = "₴", str('%.2f' % ((tcost * Childcost * single * single_child)))
                totalcost = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) + (
                            (tcost * Childcost * single * single_child) * 0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Купе")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Ковель")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)

            elif (var9.get() == "Київ" and var3.get() == 1 and var4.get() >= 1 and var5.get() >= 1):
                tcost = float(1560.5)
                Childcost = float(1460.5)
                single = float(var4.get())
                single_child = float(var5.get())
                adult_tax = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) * 0.27))
                adult_fees = "₴", str('%.2f' % ((tcost * Childcost * single * single_child)))
                totalcost = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) + (
                            (tcost * Childcost * single * single_child) * 0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Люкс (СВ)")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Київ")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Львів" and var3.get() == 1 and var4.get() >= 1 and var5.get() >= 1):
                tcost = float(1300.5)
                Childcost = float(600.5)
                single = float(var4.get())
                single_child = float(var5.get())
                adult_tax = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) * 0.27))
                adult_fees = "₴", str('%.2f' % ((tcost * Childcost * single * single_child)))
                totalcost = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) + (
                            (tcost * Childcost * single * single_child) * 0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Люкс (СВ)")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Львів")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Одеса" and var3.get() == 1 and var4.get() >= 1 and var5.get() >= 1):
                tcost = float(1420.5)
                Childcost = float(660.5)
                single = float(var4.get())
                single_child = float(var5.get())
                adult_tax = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) * 0.27))
                adult_fees = "₴", str('%.2f' % ((tcost * Childcost * single * single_child)))
                totalcost = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) + (
                            (tcost * Childcost * single * single_child) * 0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Люкс (СВ)")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Одеса")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)

            elif (var9.get() == "Ковель" and var3.get() == 1 and var4.get() >= 1 and var5.get() >= 1):
                tcost = float(980.5)
                Childcost = float(440.5)
                single = float(var4.get())
                single_child = float(var5.get())
                adult_tax = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) * 0.27))
                adult_fees = "₴", str('%.2f' % ((tcost * Childcost * single * single_child)))
                totalcost = "₴", str('%.2f' % ((tcost * Childcost * single * single_child) + (
                            (tcost * Childcost * single * single_child) * 0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Люкс (СВ)")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Ковель")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)

            elif (var9.get() == "Білгород-Дністровський" and var1.get() == 1 and var4.get() >= 1):
                tcost = float(250.5)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Плацкарт")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Акерман")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Чернігів" and var1.get() == 1 and var4.get() >= 1):
                tcost = float(200.5)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Плацкарт")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Чернігів")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Полтава" and var1.get() == 1 and var4.get() >= 1):
                tcost = float(293.80)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Плацкарт")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Полтава")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Білгород-Дністровський" and var2.get() == 1 and var4.get() >= 1):
                tcost = float(500.5)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Купе")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Акерман")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Чернігів" and var2.get() == 1 and var4.get() >= 1):
                tcost = float(400.5)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Купе")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Чернігів")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)
            elif (var9.get() == "Полтава" and var2.get() == 1 and var4.get() >= 1):
                tcost = float(507.85)
                single = float(var4.get())
                adult_tax = "₴", str('%.2f'%((tcost * single)*0.27))
                adult_fees = "₴", str('%.2f'%((tcost * single)))
                totalcost = "₴", str('%.2f'%((tcost * single)+ ((tcost * single)*0.27)))
                tax.set(adult_tax)
                subt.set(adult_fees)
                total_pay.set(totalcost)
                Ticketclass.set("Купе")
                TicketPrice.set(adult_fees)
                Child_ticket.set(chkChild.get())
                Adult_ticket.set(chkAdult.get())
                From_city.set("Чернівці")
                To_city.set("Полтава")
                fee_price.set(totalcost)
                route.set("Прямий")

                x = random.randint(117, 1050)
                randomRef = str(x)
                receipt.set("TFL" + randomRef)


        #--------------------------------------------------------------------------------------------------------------
        lblreceipt = Label(self, font=('arial',18,'bold'), fg='black',text="Системи подорожування з квитків",bd=5,width=28,padx=4,justify='center')
        lblreceipt.place(x=1340,y=75)

        lblclass1 = Label(self, font=('arial', 14, 'bold'), fg='black', text="Вагон", relief='sunken',
                           width=8, justify='center')
        lblclass1.place(x=1350,y=120)

        lblclass2 = Label(self, font=('arial', 14, 'bold'), fg='black', relief='sunken', textvariable=Ticketclass,
                           width=8, justify='center')
        lblclass2.place(x=1350,y=150)

        lblTicket1 = Label(self, font=('arial', 14, 'bold'), fg='black', text="Плата", relief='sunken',
                           width=8, justify='center')
        lblTicket1.place(x=1455,y=120)

        lblTicket2 = Label(self, font=('arial', 14, 'bold'), fg='black',  relief='sunken', textvariable=fee_price,
                           width=8, justify='center')
        lblTicket2.place(x=1455,y=150)

        lblAdult1 = Label(self, font=('arial', 14, 'bold'), fg='black', text="Дорослий", relief='sunken',
                           width=8, justify='center')
        lblAdult1.place(x=1560,y=120)

        lblAdult2 = Label(self, font=('arial', 14, 'bold'), fg='black', relief='sunken', textvariable=Adult_ticket,
                           width=8, justify='center')
        lblAdult2.place(x=1560,y=150)

        lblChild1 = Label(self, font=('arial', 14, 'bold'), fg='black', text="Дитина", relief='sunken',
                           width=8, justify='center')
        lblChild1.place(x=1665,y=120)

        lblChild2 = Label(self, font=('arial', 14, 'bold'), fg='black', relief='sunken', textvariable=Child_ticket,
                           width=8, justify='center')
        lblChild2.place(x=1665,y=150)
        # #--------------------------------------------------------------------------------------------------------------
        # lblsp = Label(self., font=('arial', 14, 'bold'), fg='black', relief='sunken', bg='lightgray',
        #                   width=36, height=2, justify='center')
        # lblsp.grid(row=2, column=0, columnspan=4)
        # #--------------------------------------------------------------------------------------------------------------
        lblFrom1 = Label(self, font=('arial', 14, 'bold'), fg='black', text='З міста', width=8,relief='sunken', justify='center')
        lblFrom1.place(x=1455,y=200)

        lblFrom2 = Label(self, font=('arial', 14, 'bold'), fg='black', width=8, relief='sunken', textvariable=From_city,
                         justify='center')
        lblFrom2.place(x=1560,y=200)
        #==============================================================================================================
        lblto1 = Label(self, font=('arial', 14, 'bold'), fg='black', text='До міста', width=8, relief='sunken',
                         justify='center')
        lblto1.place(x=1455,y=230)

        lblto2 = Label(self, font=('arial', 14, 'bold'), fg='black', width=8, relief='sunken', textvariable=To_city,
                         justify='center')
        lblto2.place(x=1560,y=230)

        lblPrice1 = Label(self, font=('arial', 14, 'bold'), fg='black', text='Плата', width=8, relief='sunken',
                         justify='center')
        lblPrice1.place(x=1455,y=260)

        lblPrice2 = Label(self, font=('arial', 14, 'bold'), fg='black', width=8, relief='sunken', textvariable=fee_price,
                         justify='center')
        lblPrice2.place(x=1560,y=260)
        # #==============================================================================================================
        # lblsp = Label(self., font=('arial', 14, 'bold'), fg='black', relief='sunken', bg='lightgray',
        #               width=36, height=2, justify='center')
        # lblsp.grid(row=6, column=0, columnspan=4)
        # #--------------------------------------------------------------------------------------------------------------
        lblRef1 = Label(self, font=('arial', 14, 'bold'), fg='black', text='Посилання', width=8, relief='sunken',
                       justify='center')
        lblRef1.place(x=1350,y=310)

        lblRef2 = Label(self, font=('arial', 14, 'bold'), fg='black', width=8, relief='sunken', textvariable=receipt,
                       justify='center')
        lblRef2.place(x=1350,y=340)

        lblTime1 = Label(self, font=('arial', 14, 'bold'), fg='black', text='Час', width=8, relief='sunken',
                          justify='center')
        lblTime1.place(x=1455,y=310)

        lblTime2 = Label(self, font=('arial', 14, 'bold'), fg='black', width=8, relief='sunken',
                          textvariable=time1,
                          justify='center')
        lblTime2.place(x=1455,y=340)

        lblDate1 = Label(self, font=('arial', 14, 'bold'), fg='black', text='Дата', width=8, relief='sunken',
                       justify='center')
        lblDate1.place(x=1560,y=310)

        lblDate2 = Label(self, font=('arial', 14, 'bold'), fg='black', width=8, relief='sunken', textvariable=date1,
                       justify='center')
        lblDate2.place(x=1560,y=340)

        lblRoute1 = Label(self, font=('arial', 14, 'bold'), fg='black', text='Маршрут', width=8, relief='sunken',
                          justify='center')
        lblRoute1.place(x=1665,y=310)

        lblRoute2 = Label(self, font=('arial', 14, 'bold'), fg='black', width=8, relief='sunken',
                          textvariable=route,
                          justify='center')
        lblRoute2.place(x=1665,y=340)
        # #--------------------------------------------------------------------------------------------------------------
        date1.set(time.strftime("%d/%m/%Y"))  # дата
        time1.set(time.strftime("%H/%M/%S"))  # час
        # #--------------------------------------------------------------------------------------------------------------
        #
        lblClass = Label(self, font=('arial',22,'bold'), fg='black', border=0, text="Тип вагона", bd=8).place(x=50,y=80)

        chkPlackart = Checkbutton(self, font=('arial',22,'bold'), border=0, fg='black', text="Плацкарт", variable=var1, onvalue=1,
                                  offvalue=0, state=NORMAL).place(x=50,y=140)
        chkKupe = Checkbutton(self, font=('arial', 22, 'bold'), border=0, fg='black', text="Купе", variable=var2, onvalue=1,
                                  offvalue=0, state=NORMAL).place(x=50,y=190)
        chkSV = Checkbutton(self, font=('arial', 22, 'bold'), border=0, fg='black', text="Люкс (СВ)", variable=var3, onvalue=1,
                                  offvalue=0, state=NORMAL).place(x=50,y=240)
        # #--------------------------------------------------------------------------------------------------------------
        lblSelect = Label(self, font=('arial', 22, 'bold'), border=0, fg='black', text="Виберіть пункт призначення", bd=8).place(x=500, y=80)
        lblDestination = Label(self, font=('arial', 22, 'bold'), border=0, fg='black', text="Пункт призначення", bd=8).place(x=450, y=130)
        cbodestination = ttk.Combobox(self,textvariable=var9, font=('arial',22,'bold'),state='readonly',width=9)
        cbodestination['value'] = (' ', 'Київ', 'Львів', 'Одеса', 'Білгород-Дністровський','Полтава', 'Чернігів')
        cbodestination.current(0)
        cbodestination.place(x=750, y=140)

        label_adult = Label(self, font=('arial', 22, 'bold'), border=0, fg='black', text="Дорослий")
        label_adult.place(x=450, y=195)
        chkAdult = Entry(self, font=('System', 20, 'bold'), bg='black', fg='red', bd=8,width=8,textvariable=var4, state=NORMAL)
        chkAdult.place(x=625, y=185)
        label_child = Label(self, font=('arial', 22, 'bold'), border=0, fg='black', text="Дитина")
        label_child.place(x=450, y=250)
        chkChild = Entry(self, font=('System', 20, 'bold'), bg='black', fg='red', bd=8,width=8,textvariable=var5, state=NORMAL)
        chkChild.place(x=625, y=240)

        # #--------------------------------------------------------------------------------------------------------------
        # lblTicketType = Label(self., font=('arial',20,'bold'), border=0, fg='black',text="Тип квитка", bd=8).grid(row=0,column=0,sticky=W)
        #
        # # chkSingle = Label(topLeft2, font=('arial', 20, 'bold'), fg='black', text="Звичайний", bd=8).grid(row=1, column=0, sticky=W)
        # # entrySingle = Entry(topLeft2, font=('System', 20, 'bold'), fg='red', textvariable=var12, bd=8, width=8).grid(row=1,
        # #                                                                                                   column=1,
        # #                                                                                                   sticky=W)
        # chkReturn = Label(self., font=('arial', 20, 'bold'), fg='black', text="Повернення", bd=8).grid(row=2, column=0, sticky=W)
        # entryReturn = Entry(self., font=('arial', 20, 'bold'), textvariable=var6, bd=8, width=8, state=DISABLED).grid(row=2,
        #                                                                                                   column=1,
        #                                                                                                   sticky=W)
        # labelcomment = Label(self.,font=('arial',20,'bold'), fg='black',text="Прокоментуйте", bd=8).grid(row=3,column=0,sticky=W)
        # entrycomment = Entry(self.,font=('arial',20,'bold'),textvariable=var7, bd=8,width=8, state=DISABLED).grid(row=3,column=1,sticky=W)
        # #--------------------------------------------------------------------------------------------------------------
        labeltax = Label(self,font=('arial',20,'bold'), border=0, fg='black', text="Державний податок",bd=8).place(x=50, y=320)
        entrytax = Entry(self,font=('arial',20,'bold'),textvariable=tax,bd=5,width=28, state=DISABLED).place(x=350, y=330)
        labelsubtotal = Label(self, font=('arial', 20, 'bold'), border=0, fg='black', text="До плати", bd=8).place(x=50, y=370)
        entrysubtotal = Entry(self, font=('arial', 20, 'bold'), textvariable=subt, bd=5, width=28, state=DISABLED).place(x=350, y=380)
        labeltotal = Label(self, font=('arial', 20, 'bold'), border=0, fg='black', text="Плата", bd=8).place(x=50, y=420)
        entrytotal = Entry(self, font=('arial', 20, 'bold'), textvariable=total_pay, bd=5, width=28, state=DISABLED).place(x=350, y=430)
        # #===================================================================================================

        # listbox_history = Listbox(self., width=60)
        # listbox_history.place(x=850, y=320)
        # #--------------------------------------------------------------------------------------------------------------
        btnTotal = Button(self,font=('arial',16,'bold'),text='Всього', width=8,height=1,padx=2,pady=16,bd=2, command=travel_cost, bg=select_bg_1,fg='white')
        btnTotal.place(x=1350,y=410)

        btnReset = Button(self, font=('arial', 16, 'bold'), text='Перезапуск', width=9, height=1, padx=4,
                          pady=16, bd=2, command=Reset, bg=select_bg_2, fg='white')
        btnReset.place(x=1450,y=410)

        btnExit = Button(self, font=('arial', 16, 'bold'), text='Вихід', width=6, height=1, padx=2,
                          pady=16, bd=2, fg='lime', bg='black', command=exit)
        btnExit.place(x=1580,y=410)
        # btnSee = Button(self., font=('arial', 16, 'bold'), text='Розглянути', width=8, height=1, padx=2,
        #                   pady=16, bd=2, fg='white', bg=select_bg_3, command=see_tickets)
        # btnSee.place(x=1670,y=410)

        menu = Menu(self, background='#000099', foreground='red', activebackground='red', activeforeground='yellow')
        self.config(menu=menu)
        self.option_add('*Background', 'yellow')

        file_menu = Menu(menu, tearoff=0, foreground='blue')
        file_menu.config(bg='pink')
        # file_menu.add_command(label='New', command=new, background='yellow')
        # file_menu.add_command(label='Open file as..')
        # file_menu.add_command(label='Save file as..', command=save_file)
        file_menu.add_command(label='Вихід', command=exit)

        help_menu = Menu(menu, tearoff=0, bg='yellow')
        help_menu.add_command(label='Допомога')
        # help_menu.add_command(label='About')
        color = Menu(help_menu)
        color.add_command(label='Кольори', command=command_help)
        color.add_command(label='Кольори шрифту', command=command_font_help)
        help_menu.add_cascade(label='Кольори', menu=color)
        menu.add_cascade(label='Файл', menu=file_menu)
        menu.add_cascade(label='Допомога', menu=help_menu)


# if __name__ == '__main__':
#      = Tk()
#     img = PhotoImage(file='Chernivtsi_station.gif')
#     background_label = Label(, image=img)
#     background_label.pack()
#     application = Train()
#     .mainloop()
